version: "3.9"

services:
  oracledb:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle-xe21
    environment:
      ORACLE_PASSWORD: "SecretPwd123" # SYS/SYSTEM password
      APP_USER: "video_app" # application user
      APP_USER_PASSWORD: "video_app" # application password
    ports:
      - "1521:1521"
    volumes:
      - ./Database/oradata:/opt/oracle/oradata

  backend:
    build:
      context: .
      dockerfile: dockerfile.backend
    container_name: movie-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracledb:1521/XEPDB1
      SPRING_DATASOURCE_USERNAME: video_app
      SPRING_DATASOURCE_PASSWORD: video_app
    depends_on:
      - oracledb

  frontend:
    build:
      context: .
      dockerfile: dockerfile.frontend
    container_name: movie-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  oracle-data:
